import { colors } from './theme';

// Backward-compatible Colors export
// 새 코드는 theme.ts의 colors를 직접 import하세요
export const Colors = {
  primary: colors.primary,
  primaryLight: colors.primaryLight,
  primaryDark: colors.primaryDark,
  secondary: colors.secondary,
  secondaryLight: colors.secondaryLight,
  background: colors.background,
  surface: colors.surface,
  card: colors.card,
  surfaceSecondary: colors.divider,
  text: colors.textPrimary,
  textSecondary: colors.textSecondary,
  textTertiary: colors.textTertiary,
  textInverse: colors.textInverse,
  border: colors.border,
  borderLight: colors.divider,
  divider: colors.divider,
  error: colors.error,
  success: colors.success,
  warning: colors.warning,
  info: colors.info,
  white: '#FFFFFF',
  black: '#000000',
  kakaoYellow: colors.kakaoYellow,
  kakaoBrown: colors.kakaoBrown,
  appleBg: colors.appleBg,
  overlay: colors.overlay,
  timerBg: colors.timerBg,
  activeStep: colors.active,
  waitStep: colors.wait,
};
