spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/picook_db
    username: picook_user
    password: picook_local_pw
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8080

# JWT
jwt:
  secret: ${JWT_SECRET:}
  access-expiration: 3600000      # 1h
  refresh-expiration: 2592000000  # 30d

aws:
  s3:
    bucket: picook-bucket-dev
    region: ap-northeast-2
    access-key: ${AWS_S3_ACCESS_KEY:local-access-key}
    secret-key: ${AWS_S3_SECRET_KEY:local-secret-key}

shorts:
  ytdlp-path: C:/Users/alstn/AppData/Local/Programs/Python/Python314/Scripts/yt-dlp.exe
  ffmpeg-path: C:/Users/alstn/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.0.1-full_build/bin/ffmpeg.exe
  temp-dir: ${java.io.tmpdir}/picook-shorts

logging:
  level:
    com.picook: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
